### ISSUE TITLE
Bootloops the game

### ISSUE THREAD

**Issue by darkdex52** [HLXII/Evolve-Autoscript#1]
After installing the script on latest Evolve version 0.6.9 it makes the game infinitely refresh the page when script is enabled with Tampermonkey.

**Comment by HLXII** [comment]
How fast does the page refresh?

I set a refresh loop at every 200 seconds. This was because if you didn't refresh the page after a long time, the modal windows would lag (opening factory/smelter stuff). I might add a setting to remove the refresh if I'm not too lazy

**Comment by HLXII** [comment]
Added autoReset setting option
