### ISSUE TITLE
TypeError: window.evolve is undefined

### ISSUE THREAD

**Issue by mrigor** [HLXII/Evolve-Autoscript#2]
https://www.dropbox.com/s/h3cn5rrmldu7z96/Screenshot%202019-11-06%2015.33.20.png?dl=0
line https://github.com/HLXII/Evolve-Autoscript/blob/master/evolve_autoscript.user.js#L5363

seems to be caused by 
https://github.com/HLXII/Evolve-Autoscript/commit/f5380e733861e36b36a7709d50d4daee4c447538#diff-ef5d1fb3b43b50cc3e5b0e72f62d93b7
you took out module injection but window doesn't have 'evolve' exposed?

**Comment by HLXII** [comment]
A new game update changed the way the game scripts work.

Have you gone onto the Settings tab and enabled script support?

**Comment by mrigor** [comment]
That did it, thanks. Perhaps installation readme needs to mention this, or flip it on your own?
