### ISSUE TITLE
Your Autoscript settings

### ISSUE THREAD

**Issue by Jerokhna** [HLXII/Evolve-Autoscript#3]
The way you have things prioritized puts everything into starvation deathloop. Really needs some work.

**Comment by HLXII** [comment]
Thanks for the constructive feedback!

I'll be sure to look into this issue. You've given me a lot of information to work off of, so I'm sure I'll be able to determine the exact setting that causes this problem. Why, with such a descriptive explanation on the issue at hand, I'm sure it'll take me months to sort through all the information you've given me. So, don't be surprised if I don't get back to you soon.

**Comment by Jerokhna** [comment]
You need a clear identifier of priority values. Is 1 high or low? If low then your script settings of 1 for farmers and 2 for hunters means you'll never sustain any population. Outside of that, some research priorities are backwards and prolong reaching MAD or even Bioseed by an extra day. But again, it doesn't help not knowing what is high or low priority. Might be helpful to have that as a tooltip. Also the option to reset all settings back to default after importing would be nice. And the complaint was about your settings for your own autoscript and not so much the script itself.

**Comment by Jerokhna** [comment]
Also, your personal priority values will sell off all cement, coal, steel and titanium before the research is done for generating them. This is most critical when it comes to steel and titanium as you can't make any outside of combat without the research. If I could get the high/low identifier, I could rework the prioritization list to function from pre-MAD to blackhole and submit those values to you.

Currently, autoprioritize, autotax, autoemploy, autosmelter, autofactory, autotrade, and a few others are all turned off because of this deathloop issue due to priority values. The only things that run without problem are the autoresearch, autostorage and autocombat.

**Comment by HLXII** [comment]
Higher Numbers = Higher Priority.

The script itself doesn't have any pre-built settings. a factory reset would set most things to 0, which would make the script go haywire. I'll add it in sometime though.

My current Saved Settings works for me, I don't quite understand what you mean by starvation death loop.

**Comment by Jerokhna** [comment]
Did Madagascar tree and dumps all people on quarry and zero hunters. But
other races have the same issues of starving out your producers. With the
research flaws, unless you are already with dual worship/space, the
settings kill itself. Not meant for anyone below mutation stage of crispr.
