### ISSUE TITLE
Auto priority not working

### ISSUE THREAD

**Issue by jfalardeau** [HLXII/Evolve-Autoscript#5]
The script seems to be locked in a loop of error, which blocks the script to do any task except auto click resources. See picture
(Thank you for all your hard work)
![image](https://user-images.githubusercontent.com/25909781/69589576-851faa00-0fba-11ea-945c-14287f68641f.png)

**Comment by HLXII** [comment]
added a fix. You might need to update the script manually.

Currently though Auto Battle won't start until you have spies in the first foreign power. I need to update it soon.
