### ISSUE TITLE
Auto market no longer works after massive volume trading

### ISSUE THREAD

**Issue by pravi-samaratunga** [HLXII/Evolve-Autoscript#6]
https://github.com/HLXII/Evolve-Autoscript/blob/f7300e9eb8815bb2e9f1701c1111b9bba2a8892a/src/resources.js#L430

The above line crashes the market function, and therefore the entire script. I didn't test to see under what cases it fails, but removing that line allowed the script to function properly for the point in the game that I'm at, having built a red planet space station.

I wanted to try the update without a script at first, so I don't have data on what may have been broken by removing that line at earlier stages of the game.

**Comment by pravi-samaratunga** [comment]
Given that this is a major bug that very quickly crashes the script, my guess is you haven't run into the problem somehow? Reply if you have trouble reproducing and I'll send you the error messages, because I forgot to copy them before deleting that line. I'm using Firefox (66.0.3) on Ubuntu 14.04 in case that makes any difference. iirc it said something like `multipliers[curMarketVolume] is undefined` or some such thing.

-------
Useless praise:

I appreciate your scripting. This game is fun either way, but it helps make Evolve more of an idle game, letting me recoup some time in my day to ~~get actual work done~~ play other idle games. This is the first time I'm using a script that isn't a simple one-liner that I wrote myself for an idle game, and I'm impressed by the multitude of design considerations that you take into account. Interestingly, it doesn't feel like you've broken the game, just added another dimension to it, so the game really stays fun!

**Comment by HLXII** [comment]
The market change was implemented in 0.7.2 which breaks Auto Market. I usually play in 4star, so I never really have the market available.

I suggest turning of Auto Market for now, I'll need to update my script for 0.7.2 someday.

**Comment by HLXII** [comment]
Script version 1.3.5 updates Auto Market to use new market volume system.
